# Generated by Django 5.0.3 on 2024-04-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedimage',
            name='image_url',
            field=models.URLField(default='https://example.com/default-image-url'),
        ),
    ]
