# Generated by Django 5.0.3 on 2024-04-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_downloadedimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadedimage',
            name='downloaded_at',
        ),
        migrations.RemoveField(
            model_name='downloadedimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='downloadedimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='downloadedimage',
            name='url',
            field=models.URLField(default='https://example.com/default-url/', unique=True),
        ),
    ]
