# Generated by Django 5.0.3 on 2024-04-01 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_downloadedimage_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedimage',
            name='downloaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='downloadedimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
