# Generated by Django 5.0.3 on 2024-04-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_downloadedimage_downloaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedimage',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
