# Generated by Django 5.0.3 on 2024-04-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_downloadedimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadedimage',
            name='downloaded_at',
        ),
        migrations.RemoveField(
            model_name='downloadedimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='downloadedimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='downloadedimage',
            name='url',
            field=models.URLField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
