# Generated by Django 5.0.3 on 2024-04-01 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_downloadedimage_downloaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedimage',
            name='downloaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downloadedimage',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='downloadedimage',
            name='url',
            field=models.URLField(default='/media/images/default-image.jpg'),
        ),
    ]
