# Generated by Django 5.0.3 on 2024-04-01 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_downloadedimage_downloaded_at_downloadedimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedimage',
            name='downloaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
