# Generated by Django 5.0.3 on 2024-04-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_downloadedimage_downloaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedimage',
            name='url',
            field=models.URLField(default='/media/images/default-image.jpg', unique=True),
        ),
    ]
