# Generated by Django 5.0.3 on 2024-04-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_downloadedimage_url_downloadedimage_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedimage',
            name='image_url',
            field=models.URLField(default='/media/images/default-image.jpg'),
        ),
    ]
